# --- GLOBAL / DEFAULT (Your Local Machine) ---
server:
  port: 8085

spring:
  application:
    name: parking-management-system
  docker:
    compose:
      # This stops Spring from trying to launch Docker automatically
      # when you run 'mvn spring-boot:run' locally.
      enabled: false
  datasource:
    # Local path: Saves to your project folder
    url: jdbc:h2:file:./data/modulith_db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update # Keeps data between restarts
  h2:
    console:
      enabled: true

---
# --- DOCKER PROFILE ---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    # Docker path: Points to the volume we will create
    url: jdbc:h2:file:/opt/h2-data/modulith_db;DB_CLOSE_DELAY=-1
  h2:
    console:
      settings:
        # Crucial: Allows you to access the console from your laptop browser
        web-allow-others: true
